### ISSUE TITLE
Music from SoundtrackEditor and remaning Chatterer sources

### ISSUE THREAD

**Issue by KvaNTy** [ensou04/RocketSoundEnhancement#10] opened 2022-03-26 21:45 UTC
Hi. So I ran your old logging line in *ApplySettings()* while in orbit.
```C#
Debug.Log("[RSE]: " + source.name + " of " + source.clip.name + " : isBypassed " + source.bypassListenerEffects);
```
And got this:
```
[RSE]: rbr_beep_player_3 of Chatterer/Sounds/beeps/3beeps : isBypassed True
[RSE]: rbr_beep_player_2 of Chatterer/Sounds/beeps/beep-04 : isBypassed True
[RSE]: rbr_beep_player_1 of Chatterer/Sounds/beeps/3beeps1000 : isBypassed True

[RSE]: rbr_background_player_2 of Chatterer/Sounds/AAE/background/drni__gas-stove-space-ship : isBypassed False
[RSE]: rbr_background_player_1 of Chatterer/Sounds/AAE/background/ch0cchi__alien-ship-idle : isBypassed False
[RSE]: New Game Object of Chatterer/Sounds/AAE/wind/mario1298__weak-wind : isBypassed False
[RSE]: New Game Object of Chatterer/Sounds/AAE/effect/airlock : isBypassed False
[RSE]: New Game Object of Chatterer/Sounds/AAE/effect/breathing : isBypassed False

[RSE]: rbr_chatter_player of Chatterer/Sounds/chatter/quindar_02 : isBypassed True
[RSE]: rbr_chatter_player of Chatterer/Sounds/chatter/quindar_01 : isBypassed True
[RSE]: rbr_chatter_player of Chatterer/Sounds/chatter/sts61c/capsule/capsule_08 : isBypassed True
[RSE]: rbr_chatter_player of Chatterer/Sounds/chatter/expedition51/capcom/capcom_03 : isBypassed True

[RSE]: SoundtrackEditor of SKRD_Transfer_Windows/Music/8-MyCapsuleMySnacksAndMe : isBypassed False

[RSE]: MusicLogic of none : isBypassed True
[RSE]: MusicLogic of none : isBypassed True
```
First issue was muffled music (that's why I looked at code in the first place). Fortunately it could be easily fixed by handling SoundtrackEditor just as stock music logic.

As for Chatterer, I assume when you turn off "Affect Chatterer" in options, RSE is supposed to completely ignore everything related to it. That's why I'm not sure how these sources have been missed (*maybe because I also have Chatterer Extended?*), or is it the intended behavior?

I'm gonna make PR for Soundtrack Editor fix, and one for chatterer in case everything is correct.

**Comment by ensou04** [comment] 2022-03-28 01:38
merged this into master.
some of the chatterer sounds unaffected was intended but after testing a while i did find it off putting that you could hear ambience in space so might as well grab them. I usually disable those sounds in chatterer because it has some clicking in the loop sounds so i pretty much forgot they existed.

**Closed** 2022-03-28 02:44 UTC
