### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Ynscription** [ensou04/RocketSoundEnhancement#23] opened 2023-02-19 12:40 UTC
Everytime a vessel is flown the memory usage increases and never goes down, eventually crashing the game due to a lack of memory.
Here's the readout of Task Manager:
![image](https://user-images.githubusercontent.com/6177465/219948484-c4125eab-f7f0-465e-a563-8b5bd6010526.png)

After uninstalling the mod this doesn't happen.

**Comment by JonnyOThan** [comment] 2023-03-07 00:02
Dupe of #17

**Closed** 2023-03-07 13:54 UTC
Labels: duplicate
